// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.23.4
// source: meta/flatten.proto

package meta

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FlattenRules struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Reserved *Reserved `protobuf:"bytes,1,opt,name=reserved,proto3,oneof" json:"reserved,omitempty"`
}

func (x *FlattenRules) Reset() {
	*x = FlattenRules{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meta_flatten_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FlattenRules) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlattenRules) ProtoMessage() {}

func (x *FlattenRules) ProtoReflect() protoreflect.Message {
	mi := &file_meta_flatten_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlattenRules.ProtoReflect.Descriptor instead.
func (*FlattenRules) Descriptor() ([]byte, []int) {
	return file_meta_flatten_proto_rawDescGZIP(), []int{0}
}

func (x *FlattenRules) GetReserved() *Reserved {
	if x != nil {
		return x.Reserved
	}
	return nil
}

type Reserved struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Min *int32 `protobuf:"varint,1,opt,name=min,proto3,oneof" json:"min,omitempty"`
	Max *int32 `protobuf:"varint,2,opt,name=max,proto3,oneof" json:"max,omitempty"`
}

func (x *Reserved) Reset() {
	*x = Reserved{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meta_flatten_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Reserved) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reserved) ProtoMessage() {}

func (x *Reserved) ProtoReflect() protoreflect.Message {
	mi := &file_meta_flatten_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reserved.ProtoReflect.Descriptor instead.
func (*Reserved) Descriptor() ([]byte, []int) {
	return file_meta_flatten_proto_rawDescGZIP(), []int{1}
}

func (x *Reserved) GetMin() int32 {
	if x != nil && x.Min != nil {
		return *x.Min
	}
	return 0
}

func (x *Reserved) GetMax() int32 {
	if x != nil && x.Max != nil {
		return *x.Max
	}
	return 0
}

var file_meta_flatten_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*FlattenRules)(nil),
		Field:         1423,
		Name:          "flatten.flatten_rule",
		Tag:           "bytes,1423,opt,name=flatten_rule",
		Filename:      "meta/flatten.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         1424,
		Name:          "flatten.flatten",
		Tag:           "varint,1424,opt,name=flatten",
		Filename:      "meta/flatten.proto",
	},
}

// Extension fields to descriptorpb.FieldOptions.
var (
	// optional flatten.FlattenRules flatten_rule = 1423;
	E_FlattenRule = &file_meta_flatten_proto_extTypes[0]
	// optional bool flatten = 1424;
	E_Flatten = &file_meta_flatten_proto_extTypes[1]
)

var File_meta_flatten_proto protoreflect.FileDescriptor

var file_meta_flatten_proto_rawDesc = []byte{
	0x0a, 0x12, 0x6d, 0x65, 0x74, 0x61, 0x2f, 0x66, 0x6c, 0x61, 0x74, 0x74, 0x65, 0x6e, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x66, 0x6c, 0x61, 0x74, 0x74, 0x65, 0x6e, 0x1a, 0x20, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x4f, 0x0a, 0x0c, 0x46, 0x6c, 0x61, 0x74, 0x74, 0x65, 0x6e, 0x52, 0x75, 0x6c, 0x65, 0x73, 0x12,
	0x32, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x11, 0x2e, 0x66, 0x6c, 0x61, 0x74, 0x74, 0x65, 0x6e, 0x2e, 0x52, 0x65, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x64, 0x48, 0x00, 0x52, 0x08, 0x72, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x64,
	0x88, 0x01, 0x01, 0x42, 0x0b, 0x0a, 0x09, 0x5f, 0x72, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x64,
	0x22, 0x48, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x64, 0x12, 0x15, 0x0a, 0x03,
	0x6d, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x48, 0x00, 0x52, 0x03, 0x6d, 0x69, 0x6e,
	0x88, 0x01, 0x01, 0x12, 0x15, 0x0a, 0x03, 0x6d, 0x61, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x48, 0x01, 0x52, 0x03, 0x6d, 0x61, 0x78, 0x88, 0x01, 0x01, 0x42, 0x06, 0x0a, 0x04, 0x5f, 0x6d,
	0x69, 0x6e, 0x42, 0x06, 0x0a, 0x04, 0x5f, 0x6d, 0x61, 0x78, 0x3a, 0x5b, 0x0a, 0x0c, 0x66, 0x6c,
	0x61, 0x74, 0x74, 0x65, 0x6e, 0x5f, 0x72, 0x75, 0x6c, 0x65, 0x12, 0x1d, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x46, 0x69, 0x65,
	0x6c, 0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x8f, 0x0b, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x15, 0x2e, 0x66, 0x6c, 0x61, 0x74, 0x74, 0x65, 0x6e, 0x2e, 0x46, 0x6c, 0x61, 0x74, 0x74,
	0x65, 0x6e, 0x52, 0x75, 0x6c, 0x65, 0x73, 0x52, 0x0b, 0x66, 0x6c, 0x61, 0x74, 0x74, 0x65, 0x6e,
	0x52, 0x75, 0x6c, 0x65, 0x88, 0x01, 0x01, 0x3a, 0x3b, 0x0a, 0x07, 0x66, 0x6c, 0x61, 0x74, 0x74,
	0x65, 0x6e, 0x12, 0x1d, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x18, 0x90, 0x0b, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x66, 0x6c, 0x61, 0x74, 0x74, 0x65,
	0x6e, 0x88, 0x01, 0x01, 0x42, 0x3b, 0x5a, 0x39, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x67,
	0x6f, 0x6c, 0x61, 0x6e, 0x67, 0x2e, 0x6f, 0x72, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2f, 0x63, 0x6d, 0x64, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2d, 0x67, 0x65,
	0x6e, 0x2d, 0x67, 0x6f, 0x2d, 0x66, 0x78, 0x2f, 0x6d, 0x65, 0x74, 0x61, 0x3b, 0x6d, 0x65, 0x74,
	0x61, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_meta_flatten_proto_rawDescOnce sync.Once
	file_meta_flatten_proto_rawDescData = file_meta_flatten_proto_rawDesc
)

func file_meta_flatten_proto_rawDescGZIP() []byte {
	file_meta_flatten_proto_rawDescOnce.Do(func() {
		file_meta_flatten_proto_rawDescData = protoimpl.X.CompressGZIP(file_meta_flatten_proto_rawDescData)
	})
	return file_meta_flatten_proto_rawDescData
}

var file_meta_flatten_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_meta_flatten_proto_goTypes = []interface{}{
	(*FlattenRules)(nil),              // 0: flatten.FlattenRules
	(*Reserved)(nil),                  // 1: flatten.Reserved
	(*descriptorpb.FieldOptions)(nil), // 2: google.protobuf.FieldOptions
}
var file_meta_flatten_proto_depIdxs = []int32{
	1, // 0: flatten.FlattenRules.reserved:type_name -> flatten.Reserved
	2, // 1: flatten.flatten_rule:extendee -> google.protobuf.FieldOptions
	2, // 2: flatten.flatten:extendee -> google.protobuf.FieldOptions
	0, // 3: flatten.flatten_rule:type_name -> flatten.FlattenRules
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	3, // [3:4] is the sub-list for extension type_name
	1, // [1:3] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_meta_flatten_proto_init() }
func file_meta_flatten_proto_init() {
	if File_meta_flatten_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_meta_flatten_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FlattenRules); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_meta_flatten_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Reserved); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_meta_flatten_proto_msgTypes[0].OneofWrappers = []interface{}{}
	file_meta_flatten_proto_msgTypes[1].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_meta_flatten_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 2,
			NumServices:   0,
		},
		GoTypes:           file_meta_flatten_proto_goTypes,
		DependencyIndexes: file_meta_flatten_proto_depIdxs,
		MessageInfos:      file_meta_flatten_proto_msgTypes,
		ExtensionInfos:    file_meta_flatten_proto_extTypes,
	}.Build()
	File_meta_flatten_proto = out.File
	file_meta_flatten_proto_rawDesc = nil
	file_meta_flatten_proto_goTypes = nil
	file_meta_flatten_proto_depIdxs = nil
}
